<a href="https://colab.research.google.com/github/2303A51045/PDS_B16_1045/blob/main/Lab_3_B16_1045.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

print("Matrix A:\n", A)
print("Matrix B:\n", B)

add_result = np.add(A, B)
sub_result = np.subtract(A, B)

print("\nMatrix Addition:\n", add_result)
print("\nMatrix Subtraction:\n", sub_result)

print("\nManual Check (A[0,0] + B[0,0]):", A[0,0] + B[0,0])
print("Manual Check (A[0,0] - B[0,0]):", A[0,0] - B[0,0])


Matrix A:
 [[4 6 8]
 [3 1 2]
 [5 6 4]]
Matrix B:
 [[4 3 7]
 [9 9 4]
 [5 8 4]]

Matrix Addition:
 [[ 8  9 15]
 [12 10  6]
 [10 14  8]]

Matrix Subtraction:
 [[ 0  3  1]
 [-6 -8 -2]
 [ 0 -2  0]]

Manual Check (A[0,0] + B[0,0]): 8
Manual Check (A[0,0] - B[0,0]): 0


In [2]:
import numpy as np

X = np.random.randint(1, 10, (3, 2))
Y = np.random.randint(1, 10, (2, 3))

print("Matrix X (3x2):\n", X)
print("Matrix Y (2x3):\n", Y)

dot_result = np.dot(X, Y)

print("\nDot Product Result (3x3):\n", dot_result)

print("\nManual Check (X[0] dot Y[:,0]):", np.dot(X[0], Y[:,0]))


Matrix X (3x2):
 [[8 7]
 [3 8]
 [6 4]]
Matrix Y (2x3):
 [[5 5 3]
 [6 1 9]]

Dot Product Result (3x3):
 [[82 47 87]
 [63 23 81]
 [54 34 54]]

Manual Check (X[0] dot Y[:,0]): 82
